<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<Version>0.0.1</Version>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.6.25358.103" />
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5-develop.4" />
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-develop.4" />
		<PackageReference Include="PropertyTools.Wpf " Version="3.1.0" />
	</ItemGroup>

	<ItemGroup>
		<MonoGameContentReference Include="**\*.mgcb" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TMMLibrary\TMMLibrary.csproj" />
	</ItemGroup>

</Project>
